name: Build libs for Unity
on:
  workflow_dispatch:
jobs:
  BuildLibs:
    name: CMake/${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows/Dll/X64/Release",
            os: windows-latest,
            config: Release,
            args: -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=ON,
            upload: "windows-x64"
          }
        - {
            name: "Linux/So/X64/Release",
            os: ubuntu-latest,
            config: Release,
            args: "-DBUILD_SHARED_LIBS=ON",
            upload: "linux-x64"
          }
        - {
            name: "MacOSX/So/ARM64/Release",
            os: macos-latest,
            config: Release,
            args: "",
            upload: "macos-arm64"
          }
        - {
            name: "Android/So/ARMv7/Release",
            os: ubuntu-latest,
            config: Release,
            args: "-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DBUILD_SHARED_LIBS=ON",
            upload: "android-armv7"
          }
        - {
            name: "Android/So/ARMv8/Release",
            os: ubuntu-latest,
            config: Release,
            args: "-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DBUILD_SHARED_LIBS=ON",
            upload: "android-armv8"
          }
        - {
            name: "iOS/Lib/arm64/Release",
            os: macos-latest,
            config: Release,
            args: -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64,
            upload: "ios"
          }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install AutoConf, AutoMake and LibTool # Needed for autogen.sh
        if: matrix.config.os == 'macos-latest'
        run: brew install autoconf automake libtool
      - name: Download models Windows
        if: contains(matrix.config.name, 'Windows')
        run: .\autogen.bat
      - name: Download models
        if: contains(matrix.config.name, 'MacOSX') ||
            contains(matrix.config.name, 'Linux') ||
            contains(matrix.config.name, 'Android') ||
            contains(matrix.config.name, 'iOS')
        run: ./autogen.sh
      - name: Install NDK
        if: contains(matrix.config.name, 'Android')
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: false
      - name: Create Work Dir
        run: mkdir build
      - name: Configure for Android
        if: contains(matrix.config.name, 'Android')
        working-directory: ./build
        run: cmake .. ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Configure for others
        if: ${{ !contains(matrix.config.name, 'Android') }}
        working-directory: ./build
        run: cmake .. ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config ${{ matrix.config.config }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-${{ matrix.config.upload }}.zip
          path: ./build
